services:
  database1:
    container_name: db1
    image: postgres
    restart: always
    command:
      - 'postgres'
      - '-c' 
      - 'max_replication_slots=10' 
      - '-c hot_standby_feedback=on'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test-db1
    ports:
      - "8010:5432"
    volumes:
      - test-db1:/var/lib/data
  database2:
    container_name: db2
    image: postgres
    restart: unless-stopped
    command:
      - 'postgres'
      - '-c'
      - 'listen_addresses=*'
      - '-c'
      - 'max_connections=100'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test-db2
    ports:
      - "8011:5432"
    volumes:
      - test-db2:/var/lib/data
volumes:
  test-db1:
  test-db2: